meta_product_name: "crad.io"
meta_title: "crad.io - credible advertising"
meta_description: "Sustainable Influencer Marketing"
meta_image: "slack-imgs.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
